In [1]:
import util.yelp as yelp
import numpy as np
from util.text_util import normalize

from hnatt import HNATT

#YELP_DATA_PATH = 'data/yelp-dataset/yelp.csv'
SAVED_MODEL_DIR = 'saved_models'
SAVED_MODEL_FILENAME = 'model.h5'
EMBEDDINGS_PATH = 'saved_models/glove.6B.100d.txt'

import pandas as pd

Using TensorFlow backend.


In [2]:
df=pd.read_csv('data/concatenated_train_pandas.csv')
#df_valid=pd.read_csv('concatenated_dev_pandas.csv')
df_test=pd.read_csv('data/concatenated_test_pandas.csv')

In [3]:
print(df["x1"][0])
print(df["x2"][0])

Man in a jersey waiting on a crowded subway platform.
the man just came back from a game


In [4]:
df["x1"] = df["x1"] + " " + df["x2"]
#df_valid["x1"] = df_valid["x1"] + " " + df_valid["x2"]
df_test["x1"] = df_test["x1"] + " " + df_test["x2"]


In [5]:
print(df["x1"][0])

Man in a jersey waiting on a crowded subway platform. the man just came back from a game


In [6]:
print(df_test['x1'][:5])


0    These girls are having a great time looking fo...
1    A moving truck with a ramp still attached. A m...
2    A group of people stand near and on a large bl...
3    A group of people stand near and on a large bl...
4    A woman lowering ballast on a boat. The captai...
Name: x1, dtype: object


In [21]:
#for row in df_test.itertuples():
 #   print(row.x1)

These girls are having a great time looking for seashells. The girls are happy.
A moving truck with a ramp still attached. A moving truck being disassembled.
A group of people stand near and on a large black square on the ground with some yellow writing on it. a person lies on the couch
A group of people stand near and on a large black square on the ground with some yellow writing on it. a group of people wait
A woman lowering ballast on a boat. The captain of the boat is preparing for rough waters.
Two men with graying beards share a laugh while enjoying the nice weather. Men are laughing together on a nice day.
A man in a black jacket standing beside a green mailbox thoroughly soiled by a group of pigeons that are nearby. A man is outdoors
Three men dressed in white shirts and white hats, (two with baseball caps, the leader with a white construction helmet), pounding sticks on steel and plastic drums. Three brothers pound on some drums
All reptiles grow throughout their lives and are

and the more simple a machine, the  more valuable it is. A complex machine is described by: it is made of more than one simple machine.
A painter with a gray t-shirt and tatted arm sketches a mural with extreme precision and focus. A painter is doing a watercolor painting.
A crowd of people fill the street in front of a McDonald's. The people are hungry.
There are a group of track runners bracing to take off. The track runners are all black ethniticity
A man rides a bicycle while a young girl holds onto the back of him. The man is sitting on the ground.
Woman wearing green pants, blue jacket and sunhat carrying food in baskets that are hung over her shoulder. They walk along carrying a bounty of food
Families with strollers waiting in front of a carousel. Some people are outside
The man in the dark maroon shirt is kicking something. the guy kicked his hat
A black man in a white uniform makes a spectacular reverse slam dunk to the crowd's amazement. the man is playing
Many bird species,

A golden dog bounds across the snow-covered hill. A golden car bounds across the snow-covered highway.
A young black man is getting his hair buzzed off. The man has long hair.
One example is when a boil water alert occurs. One example of matter is water.
A motorcyclist is flying through the air above a dirt path. The person is riding a motorcycle
Adults lay salmon eggs in fast moving, freshwater streams and rivers. Jet streams are fast moving rivers of air that are going in opposite directions called.
A woman wearing white and black carries a serving tray. A woman wearing white and black grips a steering wheel with both hands as she evades the police.
A young redheaded girl, wearing a yellow shirt, black pants, and sneakers, jumping in a grassy field with blue skies and wispy clouds in the background. A boy jumps in a grassy field
A man stands on one hand in the street while a crowd watches. The kid is standing on two hands in the street.
An Asian woman enjoys a nice treat A lady is ta

Phone to her ear, a woman bends forward at the side of a busy street. Phone to her ear, a woman bends slowly forward
A man and his son riding bikes down the sidewalk. a man and a boy were riding bikes through town on the sidewalk
A man is holding an accordion while leaning against a brown fence that overlooks some water. An accordion player leans against his fence
A little boy punching out flashcards from the cardboard they came in. A boy punches his new flashcards from the carboard they came i.
Three children, two boys and a girl, are playing with the swings on a playground with residential houses in the background. The two boys and one girl are limbless.
A teenage girl in a crowd of people looking up at something. there was a group of people present
A young boy plays on a pile of rocks. A boy is playing army with action figures on rocks.
Soil Well-drained sandy loam soils are preferred. This statement best describes sandy soils: sandy soils allow water to drain quickly.
Snow and ice 

Four men in the forest move a cannon down the path. The men are preparing to siege a castle.
Three young men in a kitchen standing around a stove, one of them is stirring something in a pot. Three people are standing inside a house near each other.
A man pushing a hand-truck of boxes is bending over to pick up a pear. A happy man is picking up a pear.
Two girls are kneeling on the ground. Two girls kneel on the ground looking for a ring one had dropped.
Ecosystem processes, nutrient and organic matter cycling; A primary role of decomposers in an ecosystem is that they cycle matter by returning carbon and other matter to the ecosystem.
A motorist gets some air over a rough hill. A motorist is riding his bike.
By feeding on insects, frogs play an important role in maintaining the balance of our ecosystem. Beneficial fungi play a crucial role in balance of ecosystems.
A man reads the paper in a bar with green lighting. The man is climbing a mountain.
A crowd and two males dressed in diffe

A girl is blowing a huge bubble. A girl is blowing many tiny bubbles.
One lady is looking at a blue box while the shorter lady is looking at something on her phone at the grocery store. one lady eats a box while the other fights a tiger
A performer plays an instrument for the audience. The performer has a flute.
A silhouette stands at the top of a bowling lane as the ball is about to impact the pins while neon lights race overhead. The bowler who just rolled in the bright, noisy alley is hoping for a strike.
They are divided into animals with a vertebral column or backbone and animals without one. Backbone is another name for the vertebral column.
Several women in headscarves are standing in a cobbled courtyard. Several women wearing headscarves stand and talk to each other in a cobbled courtyard.
A small boy wearing a blue shirt plays in the kiddie pool. Boy playing in the sandbox
Try to water only in the evening or very early morning to minimize evaporation. Watering plants and grass

Workers at Basking Robbins are filling orders. Workers busy in handling orders
Group of people wearing black shirts riding in an open top vehicle. The driver was wearing a purple shirt.
A historic-looking building. The town hall
A young man in jeans and a red shirt, wearing yellow gloves, holds a tree branch. A man swims across a pool
The medium-long coat is non matting with a soft texture like rabbit fur. Soft describes the texture of a kitten’s fur.
A man dressed in blue places mop inside a green bucket as he stands on a roof that overlooks a city. A man is holding a mop on a roof.
Two women are getting their pictures taken with a man in his underwear. The is one woman in the picture.
A bald person in green clothing stands in front of a brick wall. A hairy person naps.
Models of carbon flux in tropical ecosystems with emphasis on the role in the global carbon cycle. A primary role of decomposers in an ecosystem is that they cycle matter by returning carbon and other matter to the eco

In [15]:
# convert class labels into class indices
data_classes = ["entails", "neutral", "contradiction"]
df['target']=df['target'].apply(data_classes.index)
#df_valid['target']=df_valid['target'].apply(data_classes.index)
df_test['target']=df_test['target'].apply(data_classes.index)

In [16]:
print(df_test['target'][:5])

0    0
1    2
2    2
3    1
4    1
Name: target, dtype: int64


In [11]:
df=df.dropna()
#df_valid=df_valid.dropna()
df_test=df_test.dropna()

In [12]:
#df=df[:int(df.shape[0]*0.001)]
#df_valid=df_valid[:int(df_valid.shape[0]*0.001)]
#df_test=df_test[:int(df_test.shape[0]*0.001)]

In [13]:
col_text = 'x1'
col_target = 'target'

In [14]:
y_train = df[col_target]
y_test = df_test[col_target]
#y_val = val[col_target].tolist()

In [11]:
print(y_train[4])

1


In [12]:
#train_x=df["x1"]
#train_y=y_train

In [13]:
#train_y.shape

In [14]:
'''
h = HNATT()	
h.train(train_x, train_y, 
batch_size=16,
epochs=16,
embeddings_path=None)

#h.load_weights(SAVED_MODEL_DIR, SAVED_MODEL_FILENAME)



# print attention activation maps across sentences and words per sentence
activation_maps = h.activation_maps(
'they have some pretty interesting things here. i will definitely go back again.')
print(activation_maps)
'''

"\nh = HNATT()\t\nh.train(train_x, train_y, \nbatch_size=16,\nepochs=16,\nembeddings_path=None)\n\n#h.load_weights(SAVED_MODEL_DIR, SAVED_MODEL_FILENAME)\n\n\n\n# print attention activation maps across sentences and words per sentence\nactivation_maps = h.activation_maps(\n'they have some pretty interesting things here. i will definitely go back again.')\nprint(activation_maps)\n"

In [15]:
#(train_x, train_y), (test_x, test_y) = yelp.load_data(path='yelp.csv', size=1e4)

In [16]:
def to_one_hot(labels, dim=5):
	results = np.zeros((len(labels), dim))
	for i, label in enumerate(labels):
		results[i][label - 1] = 1
	return results

In [17]:
df['text_tokens'] = df['x1'].progress_apply(lambda x: normalize(x))
#train_set['len'] = train_set['text_tokens'].apply(lambda x: len(x))

train_x = np.empty((0,))
train_y = np.empty((0,))

training_len=df['x1'].shape[0]

#train_set = df[0:training_len].copy()
#train_set['len'] = train_set['text_tokens'].apply(lambda x: len(x))

train_x=df['text_tokens']
#train_y=train_set['']



train_y = to_one_hot(y_train, dim=3)
print(train_x[0])
print(train_y[0])

#test_y = to_one_hot(test_y)

100%|██████████| 572458/572458 [01:46<00:00, 5387.64it/s]


[u'man in jersey waiting on crowded subway platform', u'man just came back from game']
[1. 0. 0.]


In [17]:
# preprocess test_x , as above block

df_test['text_tokens']=df_test['x1'].progress_apply(lambda x: normalize(x))

#df['text_tokens'] = df['x1'].progress_apply(lambda x: normalize(x))
#train_set['len'] = train_set['text_tokens'].apply(lambda x: len(x))

test_x = np.empty((0,))
test_y = np.empty((0,))

test_x=df_test['text_tokens']
#train_y=train_set['']



test_y = to_one_hot(y_test, dim=3)
print(test_x[0])
print(test_y[0])



100%|██████████| 11950/11950 [00:03<00:00, 3708.61it/s]


[u'these girls are having great time looking for seashells', u'girls are happy']
[0. 0. 1.]


In [2]:
# load pretrained model
h = HNATT()
h.load_weights(SAVED_MODEL_DIR, SAVED_MODEL_FILENAME)


(None, 50, 100)
(None, 50, 100)
(None, 20, 100)


In [19]:
# test on test set
loss_and_metrics = h.test(test_x, test_y, batch_size=64)
print(loss_and_metrics)

11950/11950 [==============================] - 52s 4ms/step
[0.7628593543683135, 0.7003347279935701]


In [21]:
h.model.metrics_names

['loss', 'acc']

In [19]:
#h = HNATT()	
h.train(train_x, train_y, 
batch_size=64,
epochs=16,
embeddings_path=None,saved_model_dir=SAVED_MODEL_DIR,
saved_model_filename=SAVED_MODEL_FILENAME)

#h.load_weights(SAVED_MODEL_DIR, SAVED_MODEL_FILENAME)



# print attention activation maps across sentences and words per sentence
#activation_maps = h.activation_maps(
#'they have some pretty interesting things here. i will definitely go back again.')
#print(activation_maps)

Instructions for updating:
Use the retry module or similar alternatives.
Train on 515212 samples, validate on 57246 samples
Epoch 1/16
 13632/515212 [..............................] - ETA: 1:37:55 - loss: 0.4048 - acc: 0.8464

KeyboardInterrupt: 

In [ ]:
activation_maps = h.activation_maps(
'they have some pretty interesting things here. i will definitely go back again.')
print(activation_maps)

In [24]:
train_y[0]

array([1., 0., 0.])

In [23]:
h.model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 20, 50)            0         
_________________________________________________________________
time_distributed_2 (TimeDist (None, 20, 100)           4523200   
_________________________________________________________________
bidirectional_4 (Bidirection (None, 20, 100)           45300     
_________________________________________________________________
dense_transform_s (Dense)    (None, 20, 100)           10100     
_________________________________________________________________
sentence_attention (Attentio (None, 100)               100       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 303       
Total params: 4,579,003
Trainable params: 4,579,003
Non-trainable params: 0
_________________________________________________________________


In [5]:
text='I am going to play football, he is playing soccer'

ntext = normalize(text)
preds = h.predict([ntext])[0]
prediction = np.argmax(preds).astype(float)
print(prediction)

AttributeError: 'list' object has no attribute 'lower'