In [1]:
import util.yelp as yelp
import numpy as np
from util.text_util import normalize

from hnatt import HNATT

#YELP_DATA_PATH = 'data/yelp-dataset/yelp.csv'
SAVED_MODEL_DIR = 'saved_models'
SAVED_MODEL_FILENAME = 'model.h5'
EMBEDDINGS_PATH = 'saved_models/glove.6B.100d.txt'

import pandas as pd

Using TensorFlow backend.


In [2]:
from keras import backend as K
print(K.tensorflow_backend._get_available_gpus())

['/job:localhost/replica:0/task:0/device:GPU:0',
 '/job:localhost/replica:0/task:0/device:GPU:1']

In [3]:
df=pd.read_csv('data/preprocessing/preprocessing_scripts/output/concatenated_train_pandas.csv')
df_valid=pd.read_csv('data/preprocessing/preprocessing_scripts/output/concatenated_dev_pandas.csv')
df_test=pd.read_csv('data/concatenated_test_pandas.csv')


In [4]:
#print(df["x1"][0])
#print(df["x2"][0])

Back on the river, perched above a 150-m- (490-ft-) deep ravine, is the fairytale castle of Beynac-et-Cazenac.
Cinderella's castle was based partly upon Beynac-et-Cazenac.


In [5]:
df["x1"] = df["x1"] + " " + df["x2"]
df_valid["x1"] = df_valid["x1"] + " " + df_valid["x2"]
df_test["x1"] = df_test["x1"] + " " + df_test["x2"]


In [6]:
#print(df["x1"][5])

Dog climbing up and over and red wooden ramp. The dog is dead.


In [7]:
#print(df_test['x1'][6])


A man in a black jacket standing beside a green mailbox thoroughly soiled by a group of pigeons that are nearby. A man is outdoors


In [8]:
#print(df_valid['target'])

0        contradiction
1              entails
2              entails
3              entails
4              entails
5              neutral
6              entails
7              entails
8              entails
9              entails
10       contradiction
11       contradiction
12       contradiction
13       contradiction
14             entails
15       contradiction
16             neutral
17             neutral
18             entails
19             neutral
20       contradiction
21             entails
22             entails
23       contradiction
24             neutral
25             neutral
26             neutral
27             entails
28       contradiction
29             entails
             ...      
20948          neutral
20949          entails
20950          entails
20951          neutral
20952    contradiction
20953          entails
20954    contradiction
20955          entails
20956    contradiction
20957    contradiction
20958          neutral
20959    contradiction
20960    co

In [9]:
#for row in df_test.itertuples():
 #   print(row.x1)

In [10]:
# convert class labels into class indices
data_classes = ["entails", "neutral", "contradiction"]
df['target']=df['target'].apply(data_classes.index)
df_valid['target']=df_valid['target'].apply(data_classes.index)
df_test['target']=df_test['target'].apply(data_classes.index)

In [11]:
#print(df_test['target'][:15])

0     0
1     2
2     2
3     1
4     1
5     0
6     1
7     1
8     0
9     0
10    0
11    1
12    2
13    0
14    1
Name: target, dtype: int64


In [12]:
df=df.dropna()
df_valid=df_valid.dropna()
df_test=df_test.dropna()

In [13]:
#df=df[:int(df.shape[0]*0.001)]
#df_valid=df_valid[:int(df_valid.shape[0]*0.001)]
#df_test=df_test[:int(df_test.shape[0]*0.001)]

In [14]:
col_text = 'x1'
col_target = 'target'

In [15]:
y_train = df[col_target]
y_test = df_test[col_target]
y_val = df_valid[col_target]

In [16]:
#print(y_val[4])

0


In [17]:
#train_x=df["x1"]
#train_y=y_train

In [18]:
#train_y.shape

In [19]:
'''
h = HNATT()	
h.train(train_x, train_y, 
batch_size=16,
epochs=16,
embeddings_path=None)

#h.load_weights(SAVED_MODEL_DIR, SAVED_MODEL_FILENAME)



# print attention activation maps across sentences and words per sentence
activation_maps = h.activation_maps(
'they have some pretty interesting things here. i will definitely go back again.')
print(activation_maps)
'''

"\nh = HNATT()\t\nh.train(train_x, train_y, \nbatch_size=16,\nepochs=16,\nembeddings_path=None)\n\n#h.load_weights(SAVED_MODEL_DIR, SAVED_MODEL_FILENAME)\n\n\n\n# print attention activation maps across sentences and words per sentence\nactivation_maps = h.activation_maps(\n'they have some pretty interesting things here. i will definitely go back again.')\nprint(activation_maps)\n"

In [20]:
#(train_x, train_y), (test_x, test_y) = yelp.load_data(path='yelp.csv', size=1e4)

In [21]:
def to_one_hot(labels, dim=5):
	results = np.zeros((len(labels), dim))
	for i, label in enumerate(labels):
		results[i][label - 1] = 1
	return results

In [22]:
print('loading training set ...')
df['text_tokens'] = df['x1'].progress_apply(lambda x: normalize(x))
#train_set['len'] = train_set['text_tokens'].apply(lambda x: len(x))

train_x = np.empty((0,))
train_y = np.empty((0,))

training_len=df['x1'].shape[0]

#train_set = df[0:training_len].copy()
#train_set['len'] = train_set['text_tokens'].apply(lambda x: len(x))

train_x=df['text_tokens']
#train_y=train_set['']



train_y = to_one_hot(y_train, dim=3)
print(train_x[0])
print(train_y[0])

#test_y = to_one_hot(test_y)

100%|██████████| 965120/965120 [05:06<00:00, 3148.67it/s]


[u'back on river perched above 150-m- 490-ft- deep ravine is fairytale castle of beynac et cazenac', u"cinderella 's castle was based partly upon beynac et cazenac"]
[1. 0. 0.]


In [23]:
# preprocess test_x , as above block
print('loading test set ...')
df_test['text_tokens']=df_test['x1'].progress_apply(lambda x: normalize(x))

#df['text_tokens'] = df['x1'].progress_apply(lambda x: normalize(x))
#train_set['len'] = train_set['text_tokens'].apply(lambda x: len(x))

test_x = np.empty((0,))
test_y = np.empty((0,))

test_x=df_test['text_tokens']
#train_y=train_set['']



test_y = to_one_hot(y_test, dim=3)
print(test_x[0])
print(test_y[0])



100%|██████████| 11950/11950 [00:03<00:00, 2997.14it/s]

[u'these girls are having great time looking for seashells', u'girls are happy']
[0. 0. 1.]


In [24]:
#preprocess val_x , as above block
print('loading validation set ...')

df_valid['text_tokens']=df_valid['x1'].progress_apply(lambda x: normalize(x))

#df['text_tokens'] = df['x1'].progress_apply(lambda x: normalize(x))
#train_set['len'] = train_set['text_tokens'].apply(lambda x: len(x))

valid_x = np.empty((0,))
valid_y = np.empty((0,))

valid_x=df_valid['text_tokens']
#train_y=train_set['']



valid_y = to_one_hot(y_val, dim=3)
print(valid_x[0])
print(valid_y[0])

100%|██████████| 20978/20978 [00:07<00:00, 2781.00it/s]

[u'woman prepares to strike volleyball', u'woman is shooting basket through hoop']
[0. 1. 0.]


In [25]:
# load pretrained model
print('loading pretrained model / restoring model ...')
h = HNATT()
h.load_weights(SAVED_MODEL_DIR, SAVED_MODEL_FILENAME)


(None, 50, 100)
(None, 50, 100)
(None, 20, 100)


In [38]:
# test on test set
#loss_and_metrics = h.test(test_x, test_y, batch_size=64)
#print(loss_and_metrics)

11950/11950 [==============================] - 29s 2ms/step
[0.76285937477854, 0.7003347279935701]


In [39]:
#h.model.metrics_names

['loss', 'acc']

In [45]:
#valid_y[0]

array([0., 1., 0.])

In [26]:
#h = HNATT()	
h.train(train_x, train_y,valid_x,valid_y,
batch_size=64,
epochs=16,
embeddings_path=None,saved_model_dir=SAVED_MODEL_DIR,
saved_model_filename='mnli.h5')

#h.load_weights(SAVED_MODEL_DIR, SAVED_MODEL_FILENAME)



# print attention activation maps across sentences and words per sentence
#activation_maps = h.activation_maps(
#'they have some pretty interesting things here. i will definitely go back again.')
#print(activation_maps)

Train on 965120 samples, validate on 20978 samples
Epoch 1/16
 30144/965120 [..............................] - ETA: 1:56:28 - loss: 0.7096 - acc: 0.6871

KeyboardInterrupt: 

In [ ]:
''' 
activation_maps = h.activation_maps(
'they have some pretty interesting things here. i will definitely go back again.')
print(activation_maps)
'''

In [24]:
#train_y[0]

array([1., 0., 0.])

In [23]:
#h.model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 20, 50)            0         
_________________________________________________________________
time_distributed_2 (TimeDist (None, 20, 100)           4523200   
_________________________________________________________________
bidirectional_4 (Bidirection (None, 20, 100)           45300     
_________________________________________________________________
dense_transform_s (Dense)    (None, 20, 100)           10100     
_________________________________________________________________
sentence_attention (Attentio (None, 100)               100       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 303       
Total params: 4,579,003
Trainable params: 4,579,003
Non-trainable params: 0
_________________________________________________________________


In [9]:
'''
text='he was not well, he stayed at home only. he didnt go to office '

ntext = normalize(text)
preds = h.predict([ntext])[0]
prediction = np.argmax(preds).astype(float)
print(prediction)
'''

1.0


In [ ]:
#he is dancing with joy because its his birthday. he is very happy
# 